#ifndef _MACRO_FOR_H_
#define _MACRO_FOR_H_

#include "Macro_Utils.h"
#include "Macro_VA.h"
#include "Macro_Fn.h"

#define __MACRO_FOR(FN, ...)                            __MACRO_FOR_ROOT(FN, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_FOR_ROOT(FN, N, ...)                    __MACRO_FOR_ROOT_(FN, N, __VA_ARGS__)
#define __MACRO_FOR_ROOT_(FN, N, ...)                   __MACRO_FOR_ ##N (FN, __VA_ARGS__)

#define __MACRO_FOR_0(FN, ...)                          __MACRO_FN(FN)
#define __MACRO_FOR_1(FN, X, ...)                       __MACRO_FN(FN, X)
#define __MACRO_FOR_2(FN, X, ...)                       __MACRO_FN(FN, X) __MACRO_FOR_1(FN, __VA_ARGS__)
#define __MACRO_FOR_3(FN, X, ...)                       __MACRO_FN(FN, X) __MACRO_FOR_2(FN, __VA_ARGS__)
#define __MACRO_FOR_4(FN, X, ...)                       __MACRO_FN(FN, X) __MACRO_FOR_3(FN, __VA_ARGS__)
#define __MACRO_FOR_5(FN, X, ...)                       __MACRO_FN(FN, X) __MACRO_FOR_4(FN, __VA_ARGS__)
#define __MACRO_FOR_6(FN, X, ...)                       __MACRO_FN(FN, X) __MACRO_FOR_5(FN, __VA_ARGS__)
#define __MACRO_FOR_7(FN, X, ...)                       __MACRO_FN(FN, X) __MACRO_FOR_6(FN, __VA_ARGS__)
#define __MACRO_FOR_8(FN, X, ...)                       __MACRO_FN(FN, X) __MACRO_FOR_7(FN, __VA_ARGS__)
#define __MACRO_FOR_9(FN, X, ...)                       __MACRO_FN(FN, X) __MACRO_FOR_8(FN, __VA_ARGS__)
#define __MACRO_FOR_10(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_9(FN, __VA_ARGS__)
#define __MACRO_FOR_11(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_10(FN, __VA_ARGS__)
#define __MACRO_FOR_12(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_11(FN, __VA_ARGS__)
#define __MACRO_FOR_13(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_12(FN, __VA_ARGS__)
#define __MACRO_FOR_14(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_13(FN, __VA_ARGS__)
#define __MACRO_FOR_15(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_14(FN, __VA_ARGS__)
#define __MACRO_FOR_16(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_15(FN, __VA_ARGS__)
#define __MACRO_FOR_17(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_16(FN, __VA_ARGS__)
#define __MACRO_FOR_18(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_17(FN, __VA_ARGS__)
#define __MACRO_FOR_19(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_18(FN, __VA_ARGS__)
#define __MACRO_FOR_20(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_19(FN, __VA_ARGS__)
#define __MACRO_FOR_21(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_20(FN, __VA_ARGS__)
#define __MACRO_FOR_22(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_21(FN, __VA_ARGS__)
#define __MACRO_FOR_23(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_22(FN, __VA_ARGS__)
#define __MACRO_FOR_24(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_23(FN, __VA_ARGS__)
#define __MACRO_FOR_25(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_24(FN, __VA_ARGS__)
#define __MACRO_FOR_26(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_25(FN, __VA_ARGS__)
#define __MACRO_FOR_27(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_26(FN, __VA_ARGS__)
#define __MACRO_FOR_28(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_27(FN, __VA_ARGS__)
#define __MACRO_FOR_29(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_28(FN, __VA_ARGS__)
#define __MACRO_FOR_30(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_29(FN, __VA_ARGS__)
#define __MACRO_FOR_31(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_30(FN, __VA_ARGS__)
#define __MACRO_FOR_32(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_31(FN, __VA_ARGS__)
#define __MACRO_FOR_33(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_32(FN, __VA_ARGS__)
#define __MACRO_FOR_34(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_33(FN, __VA_ARGS__)
#define __MACRO_FOR_35(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_34(FN, __VA_ARGS__)
#define __MACRO_FOR_36(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_35(FN, __VA_ARGS__)
#define __MACRO_FOR_37(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_36(FN, __VA_ARGS__)
#define __MACRO_FOR_38(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_37(FN, __VA_ARGS__)
#define __MACRO_FOR_39(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_38(FN, __VA_ARGS__)
#define __MACRO_FOR_40(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_39(FN, __VA_ARGS__)
#define __MACRO_FOR_41(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_40(FN, __VA_ARGS__)
#define __MACRO_FOR_42(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_41(FN, __VA_ARGS__)
#define __MACRO_FOR_43(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_42(FN, __VA_ARGS__)
#define __MACRO_FOR_44(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_43(FN, __VA_ARGS__)
#define __MACRO_FOR_45(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_44(FN, __VA_ARGS__)
#define __MACRO_FOR_46(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_45(FN, __VA_ARGS__)
#define __MACRO_FOR_47(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_46(FN, __VA_ARGS__)
#define __MACRO_FOR_48(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_47(FN, __VA_ARGS__)
#define __MACRO_FOR_49(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_48(FN, __VA_ARGS__)
#define __MACRO_FOR_50(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_49(FN, __VA_ARGS__)
#define __MACRO_FOR_51(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_50(FN, __VA_ARGS__)
#define __MACRO_FOR_52(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_51(FN, __VA_ARGS__)
#define __MACRO_FOR_53(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_52(FN, __VA_ARGS__)
#define __MACRO_FOR_54(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_53(FN, __VA_ARGS__)
#define __MACRO_FOR_55(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_54(FN, __VA_ARGS__)
#define __MACRO_FOR_56(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_55(FN, __VA_ARGS__)
#define __MACRO_FOR_57(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_56(FN, __VA_ARGS__)
#define __MACRO_FOR_58(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_57(FN, __VA_ARGS__)
#define __MACRO_FOR_59(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_58(FN, __VA_ARGS__)
#define __MACRO_FOR_60(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_59(FN, __VA_ARGS__)
#define __MACRO_FOR_61(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_60(FN, __VA_ARGS__)
#define __MACRO_FOR_62(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_61(FN, __VA_ARGS__)
#define __MACRO_FOR_63(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_62(FN, __VA_ARGS__)
#define __MACRO_FOR_64(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_63(FN, __VA_ARGS__)
#define __MACRO_FOR_65(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_64(FN, __VA_ARGS__)
#define __MACRO_FOR_66(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_65(FN, __VA_ARGS__)
#define __MACRO_FOR_67(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_66(FN, __VA_ARGS__)
#define __MACRO_FOR_68(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_67(FN, __VA_ARGS__)
#define __MACRO_FOR_69(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_68(FN, __VA_ARGS__)
#define __MACRO_FOR_70(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_69(FN, __VA_ARGS__)
#define __MACRO_FOR_71(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_70(FN, __VA_ARGS__)
#define __MACRO_FOR_72(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_71(FN, __VA_ARGS__)
#define __MACRO_FOR_73(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_72(FN, __VA_ARGS__)
#define __MACRO_FOR_74(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_73(FN, __VA_ARGS__)
#define __MACRO_FOR_75(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_74(FN, __VA_ARGS__)
#define __MACRO_FOR_76(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_75(FN, __VA_ARGS__)
#define __MACRO_FOR_77(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_76(FN, __VA_ARGS__)
#define __MACRO_FOR_78(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_77(FN, __VA_ARGS__)
#define __MACRO_FOR_79(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_78(FN, __VA_ARGS__)
#define __MACRO_FOR_80(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_79(FN, __VA_ARGS__)
#define __MACRO_FOR_81(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_80(FN, __VA_ARGS__)
#define __MACRO_FOR_82(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_81(FN, __VA_ARGS__)
#define __MACRO_FOR_83(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_82(FN, __VA_ARGS__)
#define __MACRO_FOR_84(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_83(FN, __VA_ARGS__)
#define __MACRO_FOR_85(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_84(FN, __VA_ARGS__)
#define __MACRO_FOR_86(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_85(FN, __VA_ARGS__)
#define __MACRO_FOR_87(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_86(FN, __VA_ARGS__)
#define __MACRO_FOR_88(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_87(FN, __VA_ARGS__)
#define __MACRO_FOR_89(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_88(FN, __VA_ARGS__)
#define __MACRO_FOR_90(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_89(FN, __VA_ARGS__)
#define __MACRO_FOR_91(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_90(FN, __VA_ARGS__)
#define __MACRO_FOR_92(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_91(FN, __VA_ARGS__)
#define __MACRO_FOR_93(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_92(FN, __VA_ARGS__)
#define __MACRO_FOR_94(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_93(FN, __VA_ARGS__)
#define __MACRO_FOR_95(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_94(FN, __VA_ARGS__)
#define __MACRO_FOR_96(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_95(FN, __VA_ARGS__)
#define __MACRO_FOR_97(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_96(FN, __VA_ARGS__)
#define __MACRO_FOR_98(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_97(FN, __VA_ARGS__)
#define __MACRO_FOR_99(FN, X, ...)                      __MACRO_FN(FN, X) __MACRO_FOR_98(FN, __VA_ARGS__)
#define __MACRO_FOR_100(FN, X, ...)                     __MACRO_FN(FN, X) __MACRO_FOR_99(FN, __VA_ARGS__)

// ------------------------------------------------------------------------------------------------

#define __MACRO_FOR_ARG(FN, ARG, ...)                   __MACRO_FOR_ARG_ROOT(FN, ARG, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_FOR_ARG_ROOT(FN, ARG, N, ...)           __MACRO_FOR_ARG_ROOT_(FN, ARG, N, __VA_ARGS__)
#define __MACRO_FOR_ARG_ROOT_(FN, ARG, N, ...)          __MACRO_FOR_ARG_ ##N (FN, ARG, __VA_ARGS__)

#define __MACRO_FOR_ARG_0(FN, ARG, ...)                 FN(ARG)
#define __MACRO_FOR_ARG_1(FN, ARG, X, ...)              __MACRO_FN(FN, ARG, X) 
#define __MACRO_FOR_ARG_2(FN, ARG, X, ...)              __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_1(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_3(FN, ARG, X, ...)              __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_2(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_4(FN, ARG, X, ...)              __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_3(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_5(FN, ARG, X, ...)              __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_4(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_6(FN, ARG, X, ...)              __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_5(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_7(FN, ARG, X, ...)              __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_6(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_8(FN, ARG, X, ...)              __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_7(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_9(FN, ARG, X, ...)              __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_8(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_10(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_9(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_11(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_10(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_12(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_11(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_13(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_12(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_14(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_13(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_15(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_14(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_16(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_15(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_17(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_16(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_18(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_17(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_19(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_18(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_20(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_19(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_21(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_20(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_22(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_21(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_23(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_22(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_24(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_23(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_25(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_24(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_26(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_25(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_27(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_26(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_28(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_27(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_29(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_28(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_30(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_29(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_31(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_30(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_32(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_31(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_33(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_32(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_34(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_33(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_35(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_34(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_36(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_35(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_37(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_36(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_38(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_37(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_39(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_38(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_40(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_39(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_41(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_40(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_42(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_41(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_43(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_42(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_44(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_43(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_45(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_44(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_46(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_45(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_47(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_46(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_48(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_47(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_49(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_48(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_50(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_49(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_51(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_50(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_52(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_51(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_53(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_52(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_54(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_53(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_55(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_54(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_56(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_55(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_57(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_56(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_58(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_57(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_59(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_58(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_60(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_59(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_61(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_60(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_62(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_61(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_63(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_62(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_64(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_63(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_65(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_64(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_66(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_65(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_67(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_66(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_68(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_67(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_69(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_68(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_70(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_69(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_71(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_70(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_72(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_71(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_73(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_72(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_74(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_73(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_75(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_74(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_76(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_75(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_77(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_76(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_78(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_77(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_79(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_78(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_80(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_79(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_81(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_80(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_82(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_81(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_83(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_82(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_84(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_83(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_85(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_84(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_86(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_85(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_87(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_86(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_88(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_87(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_89(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_88(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_90(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_89(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_91(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_90(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_92(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_91(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_93(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_92(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_94(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_93(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_95(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_94(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_96(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_95(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_97(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_96(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_98(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_97(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_99(FN, ARG, X, ...)             __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_98(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_100(FN, ARG, X, ...)            __MACRO_FN(FN, ARG, X)  __MACRO_FOR_ARG_99(FN, ARG, __VA_ARGS__)

// ------------------------------------------------------------------------------------------------

#define __MACRO_FOR_TUPLE(FN, ...)                      __MACRO_FOR_TUPLE_ROOT(FN, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_FOR_TUPLE_ROOT(FN, N, ...)              __MACRO_FOR_TUPLE_ROOT_(FN, N, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ROOT_(FN, N, ...)             __MACRO_FOR_TUPLE_ ##N (FN, __VA_ARGS__)

#define __MACRO_FOR_TUPLE_0(FN, ...)                    __MACRO_FN(FN) 
#define __MACRO_FOR_TUPLE_1(FN, X, ...)                 __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X))
#define __MACRO_FOR_TUPLE_2(FN, X, ...)                 __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_1(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_3(FN, X, ...)                 __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_2(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_4(FN, X, ...)                 __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_3(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_5(FN, X, ...)                 __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_4(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_6(FN, X, ...)                 __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_5(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_7(FN, X, ...)                 __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_6(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_8(FN, X, ...)                 __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_7(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_9(FN, X, ...)                 __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_8(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_10(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_9(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_11(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_10(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_12(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_11(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_13(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_12(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_14(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_13(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_15(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_14(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_16(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_15(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_17(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_16(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_18(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_17(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_19(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_18(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_20(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_19(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_21(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_20(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_22(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_21(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_23(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_22(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_24(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_23(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_25(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_24(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_26(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_25(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_27(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_26(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_28(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_27(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_29(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_28(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_30(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_29(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_31(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_30(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_32(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_31(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_33(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_32(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_34(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_33(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_35(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_34(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_36(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_35(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_37(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_36(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_38(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_37(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_39(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_38(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_40(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_39(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_41(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_40(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_42(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_41(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_43(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_42(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_44(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_43(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_45(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_44(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_46(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_45(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_47(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_46(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_48(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_47(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_49(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_48(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_50(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_49(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_51(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_50(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_52(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_51(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_53(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_52(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_54(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_53(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_55(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_54(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_56(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_55(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_57(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_56(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_58(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_57(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_59(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_58(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_60(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_59(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_61(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_60(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_62(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_61(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_63(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_62(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_64(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_63(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_65(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_64(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_66(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_65(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_67(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_66(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_68(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_67(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_69(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_68(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_70(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_69(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_71(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_70(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_72(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_71(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_73(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_72(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_74(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_73(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_75(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_74(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_76(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_75(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_77(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_76(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_78(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_77(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_79(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_78(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_80(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_79(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_81(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_80(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_82(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_81(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_83(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_82(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_84(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_83(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_85(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_84(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_86(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_85(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_87(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_86(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_88(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_87(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_89(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_88(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_90(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_89(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_91(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_90(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_92(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_91(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_93(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_92(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_94(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_93(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_95(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_94(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_96(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_95(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_97(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_96(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_98(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_97(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_99(FN, X, ...)                __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_98(FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_100(FN, X, ...)               __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_TUPLE_99(FN, __VA_ARGS__)

// ------------------------------------------------------------------------------------------------

#define __MACRO_FOR_TUPLE_ARG(FN, ARG, ...)             __MACRO_FOR_TUPLE_ARG_ROOT(FN, ARG, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_FOR_TUPLE_ARG_ROOT(FN, ARG, N, ...)     __MACRO_FOR_TUPLE_ARG_ROOT_(FN, ARG, N, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_ROOT_(FN, ARG, N, ...)    __MACRO_FOR_TUPLE_ARG_ ##N (FN, ARG, __VA_ARGS__)

#define __MACRO_FOR_TUPLE_ARG_0(FN, ARG, ...)           __MACRO_FN(FN, ARG)
#define __MACRO_FOR_TUPLE_ARG_1(FN, ARG, X, ...)        __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) )
#define __MACRO_FOR_TUPLE_ARG_2(FN, ARG, X, ...)        __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_1(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_3(FN, ARG, X, ...)        __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_2(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_4(FN, ARG, X, ...)        __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_3(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_5(FN, ARG, X, ...)        __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_4(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_6(FN, ARG, X, ...)        __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_5(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_7(FN, ARG, X, ...)        __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_6(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_8(FN, ARG, X, ...)        __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_7(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_9(FN, ARG, X, ...)        __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_8(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_10(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_9(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_11(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_10(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_12(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_11(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_13(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_12(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_14(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_13(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_15(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_14(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_16(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_15(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_17(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_16(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_18(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_17(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_19(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_18(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_20(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_19(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_21(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_20(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_22(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_21(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_23(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_22(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_24(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_23(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_25(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_24(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_26(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_25(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_27(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_26(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_28(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_27(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_29(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_28(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_30(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_29(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_31(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_30(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_32(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_31(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_33(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_32(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_34(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_33(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_35(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_34(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_36(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_35(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_37(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_36(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_38(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_37(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_39(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_38(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_40(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_39(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_41(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_40(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_42(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_41(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_43(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_42(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_44(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_43(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_45(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_44(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_46(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_45(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_47(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_46(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_48(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_47(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_49(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_48(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_50(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_49(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_51(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_50(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_52(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_51(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_53(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_52(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_54(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_53(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_55(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_54(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_56(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_55(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_57(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_56(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_58(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_57(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_59(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_58(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_60(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_59(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_61(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_60(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_62(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_61(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_63(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_62(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_64(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_63(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_65(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_64(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_66(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_65(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_67(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_66(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_68(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_67(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_69(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_68(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_70(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_69(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_71(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_70(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_72(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_71(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_73(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_72(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_74(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_73(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_75(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_74(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_76(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_75(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_77(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_76(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_78(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_77(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_79(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_78(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_80(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_79(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_81(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_80(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_82(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_81(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_83(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_82(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_84(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_83(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_85(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_84(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_86(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_85(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_87(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_86(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_88(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_87(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_89(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_88(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_90(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_89(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_91(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_90(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_92(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_91(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_93(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_92(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_94(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_93(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_95(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_94(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_96(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_95(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_97(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_96(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_98(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_97(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_99(FN, ARG, X, ...)       __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_98(FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_100(FN, ARG, X, ...)      __MACRO_FN(FN, ARG, __MACRO_TUPLE_EXPAND(X) ) __MACRO_FOR_TUPLE_ARG_99(FN, ARG, __VA_ARGS__)

// ------------------------------------------------------------------------------------------------

#define __MACRO_FOR_MAP(MAP, ...)                       __MACRO_FOR_MAP_ROOT(MAP, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_FOR_MAP_ROOT(MAP, N, ...)               __MACRO_FOR_MAP_ROOT_(MAP, N, __VA_ARGS__)
#define __MACRO_FOR_MAP_ROOT_(MAP, N, ...)              __MACRO_FOR_MAP_ ##N (MAP, __VA_ARGS__)

#define __MACRO_FOR_MAP_0(MAP, ...)                     __MACRO_FN_MAP(MAP)
#define __MACRO_FOR_MAP_1(MAP, X, ...)                  __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X))
#define __MACRO_FOR_MAP_2(MAP, X, ...)                  __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_1(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_3(MAP, X, ...)                  __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_2(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_4(MAP, X, ...)                  __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_3(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_5(MAP, X, ...)                  __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_4(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_6(MAP, X, ...)                  __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_5(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_7(MAP, X, ...)                  __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_6(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_8(MAP, X, ...)                  __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_7(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_9(MAP, X, ...)                  __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_8(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_10(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_9(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_11(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_10(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_12(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_11(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_13(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_12(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_14(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_13(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_15(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_14(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_16(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_15(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_17(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_16(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_18(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_17(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_19(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_18(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_20(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_19(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_21(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_20(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_22(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_21(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_23(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_22(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_24(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_23(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_25(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_24(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_26(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_25(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_27(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_26(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_28(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_27(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_29(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_28(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_30(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_29(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_31(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_30(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_32(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_31(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_33(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_32(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_34(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_33(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_35(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_34(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_36(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_35(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_37(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_36(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_38(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_37(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_39(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_38(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_40(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_39(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_41(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_40(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_42(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_41(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_43(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_42(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_44(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_43(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_45(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_44(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_46(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_45(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_47(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_46(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_48(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_47(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_49(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_48(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_50(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_49(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_51(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_50(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_52(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_51(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_53(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_52(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_54(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_53(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_55(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_54(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_56(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_55(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_57(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_56(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_58(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_57(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_59(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_58(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_60(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_59(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_61(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_60(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_62(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_61(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_63(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_62(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_64(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_63(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_65(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_64(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_66(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_65(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_67(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_66(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_68(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_67(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_69(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_68(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_70(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_69(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_71(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_70(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_72(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_71(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_73(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_72(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_74(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_73(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_75(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_74(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_76(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_75(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_77(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_76(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_78(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_77(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_79(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_78(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_80(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_79(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_81(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_80(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_82(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_81(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_83(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_82(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_84(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_83(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_85(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_84(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_86(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_85(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_87(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_86(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_88(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_87(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_89(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_88(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_90(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_89(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_91(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_90(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_92(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_91(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_93(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_92(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_94(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_93(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_95(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_94(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_96(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_95(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_97(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_96(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_98(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_97(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_99(MAP, X, ...)                 __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_98(MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_100(MAP, X, ...)                __MACRO_FN_MAP(MAP, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_99(MAP, __VA_ARGS__)

// ------------------------------------------------------------------------------------------------

#define __MACRO_FOR_MAP_ARG(MAP, ARG, ...)              __MACRO_FOR_MAP_ARG_ROOT(MAP, ARG, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_FOR_MAP_ARG_ROOT(MAP, ARG, N, ...)      __MACRO_FOR_MAP_ARG_ROOT_(MAP, ARG, N, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_ROOT_(MAP, ARG, N, ...)     __MACRO_FOR_MAP_ARG_ ##N (MAP, ARG, __VA_ARGS__)

#define __MACRO_FOR_MAP_ARG_0(MAP, ARG, ...)            __MACRO_FN_MAP_ARG(MAP, ARG)
#define __MACRO_FOR_MAP_ARG_1(MAP, ARG, X, ...)         __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X))
#define __MACRO_FOR_MAP_ARG_2(MAP, ARG, X, ...)         __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_1(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_3(MAP, ARG, X, ...)         __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_2(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_4(MAP, ARG, X, ...)         __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_3(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_5(MAP, ARG, X, ...)         __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_4(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_6(MAP, ARG, X, ...)         __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_5(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_7(MAP, ARG, X, ...)         __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_6(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_8(MAP, ARG, X, ...)         __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_7(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_9(MAP, ARG, X, ...)         __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_8(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_10(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_9(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_11(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_10(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_12(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_11(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_13(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_12(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_14(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_13(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_15(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_14(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_16(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_15(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_17(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_16(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_18(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_17(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_19(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_18(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_20(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_19(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_21(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_20(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_22(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_21(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_23(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_22(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_24(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_23(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_25(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_24(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_26(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_25(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_27(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_26(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_28(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_27(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_29(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_28(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_30(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_29(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_31(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_30(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_32(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_31(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_33(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_32(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_34(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_33(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_35(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_34(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_36(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_35(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_37(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_36(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_38(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_37(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_39(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_38(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_40(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_39(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_41(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_40(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_42(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_41(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_43(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_42(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_44(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_43(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_45(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_44(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_46(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_45(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_47(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_46(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_48(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_47(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_49(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_48(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_50(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_49(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_51(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_50(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_52(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_51(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_53(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_52(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_54(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_53(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_55(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_54(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_56(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_55(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_57(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_56(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_58(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_57(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_59(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_58(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_60(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_59(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_61(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_60(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_62(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_61(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_63(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_62(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_64(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_63(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_65(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_64(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_66(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_65(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_67(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_66(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_68(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_67(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_69(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_68(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_70(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_69(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_71(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_70(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_72(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_71(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_73(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_72(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_74(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_73(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_75(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_74(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_76(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_75(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_77(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_76(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_78(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_77(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_79(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_78(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_80(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_79(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_81(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_80(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_82(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_81(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_83(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_82(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_84(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_83(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_85(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_84(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_86(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_85(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_87(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_86(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_88(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_87(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_89(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_88(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_90(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_89(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_91(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_90(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_92(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_91(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_93(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_92(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_94(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_93(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_95(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_94(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_96(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_95(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_97(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_96(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_98(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_97(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_99(MAP, ARG, X, ...)        __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_98(MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_100(MAP, ARG, X, ...)       __MACRO_FN_MAP_ARG(MAP, ARG, __MACRO_TUPLE_EXPAND(X)) __MACRO_FOR_MAP_ARG_99(MAP, ARG, __VA_ARGS__)


#endif // _MACRO_FOR_H_
