#ifndef _MACRO_FOR_H_
#define _MACRO_FOR_H_

#include "Macro_Utils.h"
#include "Macro_VA.h"
#include "Macro_Fn.h"

#define __MACRO_FOR(FN, ...)                            __MACRO_FOR_ROOT(FN, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_FOR_ROOT(FN, N, ...)                    __MACRO_FOR_ROOT_(FN, N, __VA_ARGS__)
#define __MACRO_FOR_ROOT_(FN, N, ...)                   __MACRO_FOR_ ##N (N, FN, __VA_ARGS__)

#define __MACRO_FOR_0(N, FN, ...)                       __MACRO_FN ##N (FN)
#define __MACRO_FOR_1(N, FN, X, ...)                    __MACRO_FN ##N (FN, X)
#define __MACRO_FOR_2(N, FN, X, ...)                    __MACRO_FN ##N (FN, X) __MACRO_FOR_1(N, FN, __VA_ARGS__)
#define __MACRO_FOR_3(N, FN, X, ...)                    __MACRO_FN ##N (FN, X) __MACRO_FOR_2(N, FN, __VA_ARGS__)
#define __MACRO_FOR_4(N, FN, X, ...)                    __MACRO_FN ##N (FN, X) __MACRO_FOR_3(N, FN, __VA_ARGS__)
#define __MACRO_FOR_5(N, FN, X, ...)                    __MACRO_FN ##N (FN, X) __MACRO_FOR_4(N, FN, __VA_ARGS__)
#define __MACRO_FOR_6(N, FN, X, ...)                    __MACRO_FN ##N (FN, X) __MACRO_FOR_5(N, FN, __VA_ARGS__)
#define __MACRO_FOR_7(N, FN, X, ...)                    __MACRO_FN ##N (FN, X) __MACRO_FOR_6(N, FN, __VA_ARGS__)
#define __MACRO_FOR_8(N, FN, X, ...)                    __MACRO_FN ##N (FN, X) __MACRO_FOR_7(N, FN, __VA_ARGS__)
#define __MACRO_FOR_9(N, FN, X, ...)                    __MACRO_FN ##N (FN, X) __MACRO_FOR_8(N, FN, __VA_ARGS__)
#define __MACRO_FOR_10(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_9(N, FN, __VA_ARGS__)
#define __MACRO_FOR_11(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_10(N, FN, __VA_ARGS__)
#define __MACRO_FOR_12(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_11(N, FN, __VA_ARGS__)
#define __MACRO_FOR_13(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_12(N, FN, __VA_ARGS__)
#define __MACRO_FOR_14(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_13(N, FN, __VA_ARGS__)
#define __MACRO_FOR_15(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_14(N, FN, __VA_ARGS__)
#define __MACRO_FOR_16(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_15(N, FN, __VA_ARGS__)
#define __MACRO_FOR_17(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_16(N, FN, __VA_ARGS__)
#define __MACRO_FOR_18(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_17(N, FN, __VA_ARGS__)
#define __MACRO_FOR_19(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_18(N, FN, __VA_ARGS__)
#define __MACRO_FOR_20(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_19(N, FN, __VA_ARGS__)
#define __MACRO_FOR_21(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_20(N, FN, __VA_ARGS__)
#define __MACRO_FOR_22(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_21(N, FN, __VA_ARGS__)
#define __MACRO_FOR_23(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_22(N, FN, __VA_ARGS__)
#define __MACRO_FOR_24(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_23(N, FN, __VA_ARGS__)
#define __MACRO_FOR_25(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_24(N, FN, __VA_ARGS__)
#define __MACRO_FOR_26(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_25(N, FN, __VA_ARGS__)
#define __MACRO_FOR_27(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_26(N, FN, __VA_ARGS__)
#define __MACRO_FOR_28(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_27(N, FN, __VA_ARGS__)
#define __MACRO_FOR_29(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_28(N, FN, __VA_ARGS__)
#define __MACRO_FOR_30(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_29(N, FN, __VA_ARGS__)
#define __MACRO_FOR_31(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_30(N, FN, __VA_ARGS__)
#define __MACRO_FOR_32(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_31(N, FN, __VA_ARGS__)
#define __MACRO_FOR_33(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_32(N, FN, __VA_ARGS__)
#define __MACRO_FOR_34(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_33(N, FN, __VA_ARGS__)
#define __MACRO_FOR_35(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_34(N, FN, __VA_ARGS__)
#define __MACRO_FOR_36(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_35(N, FN, __VA_ARGS__)
#define __MACRO_FOR_37(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_36(N, FN, __VA_ARGS__)
#define __MACRO_FOR_38(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_37(N, FN, __VA_ARGS__)
#define __MACRO_FOR_39(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_38(N, FN, __VA_ARGS__)
#define __MACRO_FOR_40(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_39(N, FN, __VA_ARGS__)
#define __MACRO_FOR_41(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_40(N, FN, __VA_ARGS__)
#define __MACRO_FOR_42(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_41(N, FN, __VA_ARGS__)
#define __MACRO_FOR_43(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_42(N, FN, __VA_ARGS__)
#define __MACRO_FOR_44(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_43(N, FN, __VA_ARGS__)
#define __MACRO_FOR_45(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_44(N, FN, __VA_ARGS__)
#define __MACRO_FOR_46(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_45(N, FN, __VA_ARGS__)
#define __MACRO_FOR_47(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_46(N, FN, __VA_ARGS__)
#define __MACRO_FOR_48(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_47(N, FN, __VA_ARGS__)
#define __MACRO_FOR_49(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_48(N, FN, __VA_ARGS__)
#define __MACRO_FOR_50(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_49(N, FN, __VA_ARGS__)
#define __MACRO_FOR_51(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_50(N, FN, __VA_ARGS__)
#define __MACRO_FOR_52(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_51(N, FN, __VA_ARGS__)
#define __MACRO_FOR_53(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_52(N, FN, __VA_ARGS__)
#define __MACRO_FOR_54(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_53(N, FN, __VA_ARGS__)
#define __MACRO_FOR_55(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_54(N, FN, __VA_ARGS__)
#define __MACRO_FOR_56(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_55(N, FN, __VA_ARGS__)
#define __MACRO_FOR_57(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_56(N, FN, __VA_ARGS__)
#define __MACRO_FOR_58(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_57(N, FN, __VA_ARGS__)
#define __MACRO_FOR_59(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_58(N, FN, __VA_ARGS__)
#define __MACRO_FOR_60(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_59(N, FN, __VA_ARGS__)
#define __MACRO_FOR_61(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_60(N, FN, __VA_ARGS__)
#define __MACRO_FOR_62(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_61(N, FN, __VA_ARGS__)
#define __MACRO_FOR_63(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_62(N, FN, __VA_ARGS__)
#define __MACRO_FOR_64(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_63(N, FN, __VA_ARGS__)
#define __MACRO_FOR_65(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_64(N, FN, __VA_ARGS__)
#define __MACRO_FOR_66(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_65(N, FN, __VA_ARGS__)
#define __MACRO_FOR_67(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_66(N, FN, __VA_ARGS__)
#define __MACRO_FOR_68(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_67(N, FN, __VA_ARGS__)
#define __MACRO_FOR_69(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_68(N, FN, __VA_ARGS__)
#define __MACRO_FOR_70(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_69(N, FN, __VA_ARGS__)
#define __MACRO_FOR_71(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_70(N, FN, __VA_ARGS__)
#define __MACRO_FOR_72(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_71(N, FN, __VA_ARGS__)
#define __MACRO_FOR_73(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_72(N, FN, __VA_ARGS__)
#define __MACRO_FOR_74(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_73(N, FN, __VA_ARGS__)
#define __MACRO_FOR_75(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_74(N, FN, __VA_ARGS__)
#define __MACRO_FOR_76(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_75(N, FN, __VA_ARGS__)
#define __MACRO_FOR_77(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_76(N, FN, __VA_ARGS__)
#define __MACRO_FOR_78(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_77(N, FN, __VA_ARGS__)
#define __MACRO_FOR_79(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_78(N, FN, __VA_ARGS__)
#define __MACRO_FOR_80(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_79(N, FN, __VA_ARGS__)
#define __MACRO_FOR_81(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_80(N, FN, __VA_ARGS__)
#define __MACRO_FOR_82(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_81(N, FN, __VA_ARGS__)
#define __MACRO_FOR_83(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_82(N, FN, __VA_ARGS__)
#define __MACRO_FOR_84(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_83(N, FN, __VA_ARGS__)
#define __MACRO_FOR_85(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_84(N, FN, __VA_ARGS__)
#define __MACRO_FOR_86(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_85(N, FN, __VA_ARGS__)
#define __MACRO_FOR_87(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_86(N, FN, __VA_ARGS__)
#define __MACRO_FOR_88(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_87(N, FN, __VA_ARGS__)
#define __MACRO_FOR_89(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_88(N, FN, __VA_ARGS__)
#define __MACRO_FOR_90(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_89(N, FN, __VA_ARGS__)
#define __MACRO_FOR_91(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_90(N, FN, __VA_ARGS__)
#define __MACRO_FOR_92(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_91(N, FN, __VA_ARGS__)
#define __MACRO_FOR_93(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_92(N, FN, __VA_ARGS__)
#define __MACRO_FOR_94(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_93(N, FN, __VA_ARGS__)
#define __MACRO_FOR_95(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_94(N, FN, __VA_ARGS__)
#define __MACRO_FOR_96(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_95(N, FN, __VA_ARGS__)
#define __MACRO_FOR_97(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_96(N, FN, __VA_ARGS__)
#define __MACRO_FOR_98(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_97(N, FN, __VA_ARGS__)
#define __MACRO_FOR_99(N, FN, X, ...)                   __MACRO_FN ##N (FN, X) __MACRO_FOR_98(N, FN, __VA_ARGS__)
#define __MACRO_FOR_100(N, FN, X, ...)                  __MACRO_FN ##N (FN, X) __MACRO_FOR_99(N, FN, __VA_ARGS__)

// ------------------------------------------------------------------------------------------------

#define __MACRO_FOR_ARG(FN, ARG, ...)                   __MACRO_FOR_ARG_ROOT(FN, ARG, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_FOR_ARG_ROOT(FN, ARG, N, ...)           __MACRO_FOR_ARG_ROOT_(FN, ARG, N, __VA_ARGS__)
#define __MACRO_FOR_ARG_ROOT_(FN, ARG, N, ...)          __MACRO_FOR_ARG_ ##N (N, FN, ARG, __VA_ARGS__)

#define __MACRO_FOR_ARG_0(N, FN, ARG, ...)              __MACRO_FNA ##N (FN, ARG)
#define __MACRO_FOR_ARG_1(N, FN, ARG, X, ...)           __MACRO_FNA ##N (FN, ARG, X) 
#define __MACRO_FOR_ARG_2(N, FN, ARG, X, ...)           __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_1(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_3(N, FN, ARG, X, ...)           __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_2(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_4(N, FN, ARG, X, ...)           __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_3(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_5(N, FN, ARG, X, ...)           __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_4(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_6(N, FN, ARG, X, ...)           __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_5(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_7(N, FN, ARG, X, ...)           __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_6(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_8(N, FN, ARG, X, ...)           __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_7(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_9(N, FN, ARG, X, ...)           __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_8(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_10(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_9(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_11(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_10(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_12(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_11(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_13(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_12(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_14(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_13(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_15(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_14(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_16(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_15(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_17(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_16(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_18(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_17(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_19(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_18(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_20(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_19(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_21(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_20(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_22(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_21(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_23(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_22(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_24(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_23(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_25(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_24(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_26(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_25(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_27(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_26(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_28(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_27(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_29(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_28(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_30(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_29(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_31(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_30(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_32(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_31(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_33(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_32(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_34(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_33(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_35(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_34(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_36(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_35(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_37(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_36(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_38(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_37(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_39(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_38(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_40(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_39(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_41(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_40(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_42(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_41(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_43(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_42(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_44(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_43(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_45(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_44(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_46(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_45(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_47(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_46(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_48(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_47(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_49(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_48(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_50(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_49(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_51(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_50(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_52(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_51(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_53(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_52(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_54(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_53(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_55(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_54(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_56(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_55(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_57(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_56(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_58(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_57(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_59(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_58(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_60(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_59(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_61(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_60(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_62(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_61(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_63(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_62(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_64(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_63(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_65(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_64(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_66(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_65(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_67(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_66(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_68(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_67(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_69(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_68(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_70(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_69(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_71(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_70(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_72(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_71(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_73(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_72(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_74(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_73(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_75(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_74(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_76(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_75(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_77(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_76(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_78(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_77(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_79(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_78(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_80(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_79(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_81(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_80(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_82(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_81(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_83(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_82(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_84(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_83(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_85(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_84(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_86(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_85(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_87(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_86(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_88(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_87(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_89(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_88(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_90(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_89(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_91(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_90(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_92(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_91(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_93(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_92(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_94(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_93(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_95(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_94(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_96(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_95(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_97(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_96(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_98(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_97(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_99(N, FN, ARG, X, ...)          __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_98(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_ARG_100(N, FN, ARG, X, ...)         __MACRO_FNA ##N (FN, ARG, X)  __MACRO_FOR_ARG_99(N, FN, ARG, __VA_ARGS__)

// ------------------------------------------------------------------------------------------------

#define __MACRO_FOR_TUPLE(FN, ...)                      __MACRO_FOR_TUPLE_ROOT(FN, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_FOR_TUPLE_ROOT(FN, N, ...)              __MACRO_FOR_TUPLE_ROOT_(FN, N, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ROOT_(FN, N, ...)             __MACRO_FOR_TUPLE_ ##N (N, FN, __VA_ARGS__)

#define __MACRO_FOR_TUPLE_0(N, FN, ...)                 __MACRO_FNT ##N (FN, FN) 
#define __MACRO_FOR_TUPLE_1(N, FN, X, ...)              __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X))
#define __MACRO_FOR_TUPLE_2(N, FN, X, ...)              __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_1(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_3(N, FN, X, ...)              __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_2(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_4(N, FN, X, ...)              __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_3(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_5(N, FN, X, ...)              __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_4(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_6(N, FN, X, ...)              __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_5(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_7(N, FN, X, ...)              __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_6(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_8(N, FN, X, ...)              __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_7(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_9(N, FN, X, ...)              __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_8(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_10(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_9(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_11(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_10(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_12(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_11(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_13(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_12(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_14(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_13(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_15(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_14(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_16(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_15(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_17(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_16(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_18(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_17(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_19(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_18(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_20(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_19(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_21(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_20(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_22(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_21(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_23(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_22(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_24(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_23(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_25(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_24(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_26(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_25(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_27(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_26(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_28(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_27(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_29(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_28(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_30(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_29(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_31(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_30(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_32(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_31(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_33(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_32(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_34(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_33(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_35(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_34(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_36(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_35(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_37(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_36(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_38(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_37(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_39(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_38(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_40(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_39(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_41(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_40(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_42(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_41(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_43(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_42(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_44(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_43(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_45(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_44(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_46(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_45(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_47(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_46(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_48(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_47(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_49(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_48(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_50(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_49(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_51(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_50(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_52(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_51(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_53(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_52(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_54(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_53(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_55(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_54(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_56(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_55(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_57(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_56(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_58(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_57(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_59(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_58(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_60(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_59(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_61(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_60(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_62(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_61(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_63(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_62(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_64(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_63(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_65(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_64(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_66(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_65(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_67(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_66(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_68(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_67(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_69(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_68(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_70(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_69(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_71(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_70(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_72(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_71(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_73(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_72(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_74(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_73(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_75(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_74(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_76(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_75(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_77(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_76(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_78(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_77(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_79(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_78(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_80(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_79(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_81(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_80(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_82(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_81(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_83(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_82(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_84(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_83(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_85(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_84(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_86(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_85(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_87(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_86(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_88(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_87(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_89(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_88(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_90(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_89(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_91(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_90(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_92(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_91(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_93(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_92(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_94(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_93(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_95(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_94(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_96(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_95(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_97(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_96(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_98(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_97(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_99(N, FN, X, ...)             __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_98(N, FN, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_100(N, FN, X, ...)            __MACRO_FNT ##N (FN, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_TUPLE_99(N, FN, __VA_ARGS__)

// ------------------------------------------------------------------------------------------------

#define __MACRO_FOR_TUPLE_ARG(FN, ARG, ...)             __MACRO_FOR_TUPLE_ARG_ROOT(FN, ARG, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_FOR_TUPLE_ARG_ROOT(FN, ARG, N, ...)     __MACRO_FOR_TUPLE_ARG_ROOT_(FN, ARG, N, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_ROOT_(FN, ARG, N, ...)    __MACRO_FOR_TUPLE_ARG_ ##N (N, FN, ARG, __VA_ARGS__)

#define __MACRO_FOR_TUPLE_ARG_0(N, FN, ARG, ...)        __MACRO_FNTA ##N (FN, ARG)
#define __MACRO_FOR_TUPLE_ARG_1(N, FN, ARG, X, ...)     __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) )
#define __MACRO_FOR_TUPLE_ARG_2(N, FN, ARG, X, ...)     __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_1(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_3(N, FN, ARG, X, ...)     __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_2(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_4(N, FN, ARG, X, ...)     __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_3(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_5(N, FN, ARG, X, ...)     __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_4(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_6(N, FN, ARG, X, ...)     __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_5(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_7(N, FN, ARG, X, ...)     __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_6(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_8(N, FN, ARG, X, ...)     __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_7(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_9(N, FN, ARG, X, ...)     __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_8(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_10(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_9(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_11(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_10(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_12(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_11(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_13(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_12(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_14(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_13(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_15(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_14(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_16(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_15(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_17(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_16(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_18(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_17(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_19(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_18(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_20(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_19(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_21(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_20(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_22(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_21(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_23(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_22(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_24(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_23(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_25(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_24(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_26(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_25(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_27(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_26(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_28(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_27(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_29(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_28(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_30(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_29(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_31(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_30(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_32(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_31(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_33(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_32(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_34(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_33(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_35(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_34(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_36(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_35(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_37(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_36(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_38(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_37(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_39(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_38(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_40(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_39(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_41(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_40(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_42(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_41(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_43(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_42(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_44(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_43(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_45(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_44(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_46(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_45(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_47(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_46(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_48(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_47(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_49(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_48(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_50(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_49(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_51(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_50(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_52(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_51(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_53(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_52(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_54(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_53(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_55(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_54(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_56(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_55(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_57(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_56(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_58(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_57(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_59(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_58(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_60(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_59(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_61(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_60(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_62(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_61(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_63(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_62(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_64(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_63(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_65(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_64(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_66(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_65(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_67(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_66(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_68(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_67(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_69(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_68(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_70(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_69(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_71(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_70(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_72(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_71(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_73(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_72(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_74(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_73(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_75(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_74(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_76(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_75(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_77(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_76(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_78(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_77(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_79(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_78(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_80(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_79(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_81(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_80(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_82(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_81(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_83(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_82(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_84(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_83(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_85(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_84(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_86(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_85(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_87(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_86(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_88(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_87(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_89(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_88(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_90(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_89(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_91(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_90(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_92(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_91(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_93(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_92(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_94(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_93(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_95(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_94(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_96(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_95(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_97(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_96(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_98(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_97(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_99(N, FN, ARG, X, ...)    __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_98(N, FN, ARG, __VA_ARGS__)
#define __MACRO_FOR_TUPLE_ARG_100(N, FN, ARG, X, ...)   __MACRO_FNTA ##N (FN, ARG, __MACRO_TUPLE_EXPANDX(N, X) ) __MACRO_FOR_TUPLE_ARG_99(N, FN, ARG, __VA_ARGS__)

// ------------------------------------------------------------------------------------------------

#define __MACRO_FOR_MAP(MAP, ...)                       __MACRO_FOR_MAP_ROOT(MAP, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_FOR_MAP_ROOT(MAP, N, ...)               __MACRO_FOR_MAP_ROOT_(MAP, N, __VA_ARGS__)
#define __MACRO_FOR_MAP_ROOT_(MAP, N, ...)              __MACRO_FOR_MAP_ ##N (N, MAP, __VA_ARGS__)

#define __MACRO_FOR_MAP_0(N, MAP, ...)                  __MACRO_FN_MAPX(M, N, MAP)
#define __MACRO_FOR_MAP_1(N, MAP, X, ...)               __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X))
#define __MACRO_FOR_MAP_2(N, MAP, X, ...)               __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_1(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_3(N, MAP, X, ...)               __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_2(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_4(N, MAP, X, ...)               __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_3(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_5(N, MAP, X, ...)               __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_4(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_6(N, MAP, X, ...)               __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_5(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_7(N, MAP, X, ...)               __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_6(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_8(N, MAP, X, ...)               __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_7(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_9(N, MAP, X, ...)               __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_8(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_10(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_9(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_11(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_10(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_12(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_11(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_13(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_12(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_14(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_13(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_15(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_14(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_16(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_15(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_17(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_16(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_18(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_17(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_19(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_18(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_20(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_19(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_21(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_20(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_22(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_21(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_23(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_22(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_24(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_23(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_25(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_24(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_26(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_25(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_27(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_26(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_28(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_27(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_29(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_28(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_30(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_29(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_31(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_30(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_32(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_31(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_33(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_32(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_34(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_33(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_35(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_34(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_36(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_35(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_37(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_36(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_38(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_37(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_39(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_38(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_40(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_39(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_41(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_40(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_42(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_41(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_43(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_42(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_44(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_43(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_45(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_44(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_46(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_45(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_47(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_46(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_48(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_47(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_49(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_48(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_50(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_49(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_51(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_50(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_52(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_51(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_53(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_52(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_54(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_53(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_55(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_54(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_56(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_55(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_57(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_56(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_58(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_57(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_59(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_58(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_60(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_59(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_61(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_60(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_62(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_61(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_63(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_62(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_64(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_63(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_65(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_64(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_66(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_65(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_67(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_66(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_68(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_67(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_69(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_68(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_70(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_69(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_71(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_70(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_72(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_71(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_73(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_72(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_74(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_73(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_75(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_74(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_76(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_75(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_77(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_76(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_78(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_77(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_79(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_78(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_80(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_79(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_81(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_80(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_82(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_81(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_83(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_82(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_84(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_83(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_85(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_84(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_86(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_85(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_87(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_86(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_88(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_87(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_89(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_88(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_90(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_89(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_91(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_90(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_92(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_91(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_93(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_92(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_94(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_93(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_95(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_94(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_96(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_95(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_97(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_96(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_98(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_97(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_99(N, MAP, X, ...)              __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_98(N, MAP, __VA_ARGS__)
#define __MACRO_FOR_MAP_100(N, MAP, X, ...)             __MACRO_FN_MAPX(M, N, MAP, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_99(N, MAP, __VA_ARGS__)

// ------------------------------------------------------------------------------------------------

#define __MACRO_FOR_MAP_ARG(MAP, ARG, ...)              __MACRO_FOR_MAP_ARG_ROOT(MAP, ARG, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_FOR_MAP_ARG_ROOT(MAP, ARG, N, ...)      __MACRO_FOR_MAP_ARG_ROOT_(MAP, ARG, N, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_ROOT_(MAP, ARG, N, ...)     __MACRO_FOR_MAP_ARG_ ##N (N, MAP, ARG, __VA_ARGS__)

#define __MACRO_FOR_MAP_ARG_0(N, MAP, ARG, ...)         __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG)
#define __MACRO_FOR_MAP_ARG_1(N, MAP, ARG, X, ...)      __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X))
#define __MACRO_FOR_MAP_ARG_2(N, MAP, ARG, X, ...)      __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_1(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_3(N, MAP, ARG, X, ...)      __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_2(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_4(N, MAP, ARG, X, ...)      __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_3(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_5(N, MAP, ARG, X, ...)      __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_4(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_6(N, MAP, ARG, X, ...)      __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_5(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_7(N, MAP, ARG, X, ...)      __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_6(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_8(N, MAP, ARG, X, ...)      __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_7(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_9(N, MAP, ARG, X, ...)      __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_8(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_10(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_9(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_11(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_10(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_12(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_11(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_13(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_12(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_14(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_13(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_15(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_14(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_16(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_15(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_17(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_16(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_18(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_17(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_19(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_18(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_20(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_19(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_21(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_20(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_22(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_21(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_23(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_22(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_24(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_23(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_25(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_24(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_26(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_25(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_27(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_26(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_28(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_27(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_29(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_28(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_30(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_29(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_31(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_30(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_32(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_31(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_33(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_32(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_34(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_33(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_35(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_34(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_36(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_35(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_37(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_36(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_38(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_37(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_39(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_38(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_40(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_39(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_41(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_40(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_42(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_41(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_43(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_42(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_44(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_43(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_45(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_44(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_46(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_45(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_47(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_46(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_48(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_47(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_49(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_48(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_50(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_49(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_51(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_50(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_52(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_51(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_53(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_52(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_54(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_53(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_55(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_54(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_56(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_55(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_57(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_56(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_58(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_57(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_59(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_58(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_60(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_59(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_61(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_60(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_62(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_61(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_63(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_62(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_64(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_63(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_65(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_64(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_66(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_65(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_67(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_66(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_68(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_67(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_69(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_68(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_70(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_69(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_71(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_70(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_72(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_71(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_73(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_72(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_74(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_73(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_75(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_74(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_76(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_75(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_77(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_76(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_78(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_77(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_79(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_78(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_80(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_79(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_81(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_80(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_82(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_81(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_83(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_82(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_84(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_83(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_85(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_84(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_86(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_85(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_87(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_86(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_88(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_87(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_89(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_88(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_90(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_89(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_91(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_90(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_92(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_91(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_93(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_92(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_94(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_93(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_95(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_94(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_96(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_95(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_97(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_96(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_98(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_97(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_99(N, MAP, ARG, X, ...)     __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_98(N, MAP, ARG, __VA_ARGS__)
#define __MACRO_FOR_MAP_ARG_100(N, MAP, ARG, X, ...)    __MACRO_FN_MAP_ARGX(MA, N, MAP, ARG, __MACRO_TUPLE_EXPANDX(N, X)) __MACRO_FOR_MAP_ARG_99(N, MAP, ARG, __VA_ARGS__)


#endif // _MACRO_FOR_H_
