#ifndef _MACRO_JOIN_H_
#define _MACRO_JOIN_H_

#include "Macro_Utils.h"
#include "Macro_VA.h"
#include "Macro_Fn.h"

#define __MACRO_JOIN(SEP, ...)                          __MACRO_JOIN_ROOT(SEP, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_JOIN_ROOT(S, N, ...)                    __MACRO_JOIN_ROOT_(S, N, __VA_ARGS__)
#define __MACRO_JOIN_ROOT_(S, N, ...)                   __MACRO_JOIN_ ##N (S, __VA_ARGS__)

#define __MACRO_JOIN_0(S, ...)                          
#define __MACRO_JOIN_1(S, X, ...)                       X
#define __MACRO_JOIN_2(S, X, ...)                       X S __MACRO_JOIN_1(S, __VA_ARGS__)
#define __MACRO_JOIN_3(S, X, ...)                       X S __MACRO_JOIN_2(S, __VA_ARGS__)
#define __MACRO_JOIN_4(S, X, ...)                       X S __MACRO_JOIN_3(S, __VA_ARGS__)
#define __MACRO_JOIN_5(S, X, ...)                       X S __MACRO_JOIN_4(S, __VA_ARGS__)
#define __MACRO_JOIN_6(S, X, ...)                       X S __MACRO_JOIN_5(S, __VA_ARGS__)
#define __MACRO_JOIN_7(S, X, ...)                       X S __MACRO_JOIN_6(S, __VA_ARGS__)
#define __MACRO_JOIN_8(S, X, ...)                       X S __MACRO_JOIN_7(S, __VA_ARGS__)
#define __MACRO_JOIN_9(S, X, ...)                       X S __MACRO_JOIN_8(S, __VA_ARGS__)
#define __MACRO_JOIN_10(S, X, ...)                      X S __MACRO_JOIN_9(S, __VA_ARGS__)
#define __MACRO_JOIN_11(S, X, ...)                      X S __MACRO_JOIN_10(S, __VA_ARGS__)
#define __MACRO_JOIN_12(S, X, ...)                      X S __MACRO_JOIN_11(S, __VA_ARGS__)
#define __MACRO_JOIN_13(S, X, ...)                      X S __MACRO_JOIN_12(S, __VA_ARGS__)
#define __MACRO_JOIN_14(S, X, ...)                      X S __MACRO_JOIN_13(S, __VA_ARGS__)
#define __MACRO_JOIN_15(S, X, ...)                      X S __MACRO_JOIN_14(S, __VA_ARGS__)
#define __MACRO_JOIN_16(S, X, ...)                      X S __MACRO_JOIN_15(S, __VA_ARGS__)
#define __MACRO_JOIN_17(S, X, ...)                      X S __MACRO_JOIN_16(S, __VA_ARGS__)
#define __MACRO_JOIN_18(S, X, ...)                      X S __MACRO_JOIN_17(S, __VA_ARGS__)
#define __MACRO_JOIN_19(S, X, ...)                      X S __MACRO_JOIN_18(S, __VA_ARGS__)
#define __MACRO_JOIN_20(S, X, ...)                      X S __MACRO_JOIN_19(S, __VA_ARGS__)
#define __MACRO_JOIN_21(S, X, ...)                      X S __MACRO_JOIN_20(S, __VA_ARGS__)
#define __MACRO_JOIN_22(S, X, ...)                      X S __MACRO_JOIN_21(S, __VA_ARGS__)
#define __MACRO_JOIN_23(S, X, ...)                      X S __MACRO_JOIN_22(S, __VA_ARGS__)
#define __MACRO_JOIN_24(S, X, ...)                      X S __MACRO_JOIN_23(S, __VA_ARGS__)
#define __MACRO_JOIN_25(S, X, ...)                      X S __MACRO_JOIN_24(S, __VA_ARGS__)
#define __MACRO_JOIN_26(S, X, ...)                      X S __MACRO_JOIN_25(S, __VA_ARGS__)
#define __MACRO_JOIN_27(S, X, ...)                      X S __MACRO_JOIN_26(S, __VA_ARGS__)
#define __MACRO_JOIN_28(S, X, ...)                      X S __MACRO_JOIN_27(S, __VA_ARGS__)
#define __MACRO_JOIN_29(S, X, ...)                      X S __MACRO_JOIN_28(S, __VA_ARGS__)
#define __MACRO_JOIN_30(S, X, ...)                      X S __MACRO_JOIN_29(S, __VA_ARGS__)
#define __MACRO_JOIN_31(S, X, ...)                      X S __MACRO_JOIN_30(S, __VA_ARGS__)
#define __MACRO_JOIN_32(S, X, ...)                      X S __MACRO_JOIN_31(S, __VA_ARGS__)
#define __MACRO_JOIN_33(S, X, ...)                      X S __MACRO_JOIN_32(S, __VA_ARGS__)
#define __MACRO_JOIN_34(S, X, ...)                      X S __MACRO_JOIN_33(S, __VA_ARGS__)
#define __MACRO_JOIN_35(S, X, ...)                      X S __MACRO_JOIN_34(S, __VA_ARGS__)
#define __MACRO_JOIN_36(S, X, ...)                      X S __MACRO_JOIN_35(S, __VA_ARGS__)
#define __MACRO_JOIN_37(S, X, ...)                      X S __MACRO_JOIN_36(S, __VA_ARGS__)
#define __MACRO_JOIN_38(S, X, ...)                      X S __MACRO_JOIN_37(S, __VA_ARGS__)
#define __MACRO_JOIN_39(S, X, ...)                      X S __MACRO_JOIN_38(S, __VA_ARGS__)
#define __MACRO_JOIN_40(S, X, ...)                      X S __MACRO_JOIN_39(S, __VA_ARGS__)
#define __MACRO_JOIN_41(S, X, ...)                      X S __MACRO_JOIN_40(S, __VA_ARGS__)
#define __MACRO_JOIN_42(S, X, ...)                      X S __MACRO_JOIN_41(S, __VA_ARGS__)
#define __MACRO_JOIN_43(S, X, ...)                      X S __MACRO_JOIN_42(S, __VA_ARGS__)
#define __MACRO_JOIN_44(S, X, ...)                      X S __MACRO_JOIN_43(S, __VA_ARGS__)
#define __MACRO_JOIN_45(S, X, ...)                      X S __MACRO_JOIN_44(S, __VA_ARGS__)
#define __MACRO_JOIN_46(S, X, ...)                      X S __MACRO_JOIN_45(S, __VA_ARGS__)
#define __MACRO_JOIN_47(S, X, ...)                      X S __MACRO_JOIN_46(S, __VA_ARGS__)
#define __MACRO_JOIN_48(S, X, ...)                      X S __MACRO_JOIN_47(S, __VA_ARGS__)
#define __MACRO_JOIN_49(S, X, ...)                      X S __MACRO_JOIN_48(S, __VA_ARGS__)
#define __MACRO_JOIN_50(S, X, ...)                      X S __MACRO_JOIN_49(S, __VA_ARGS__)
#define __MACRO_JOIN_51(S, X, ...)                      X S __MACRO_JOIN_50(S, __VA_ARGS__)
#define __MACRO_JOIN_52(S, X, ...)                      X S __MACRO_JOIN_51(S, __VA_ARGS__)
#define __MACRO_JOIN_53(S, X, ...)                      X S __MACRO_JOIN_52(S, __VA_ARGS__)
#define __MACRO_JOIN_54(S, X, ...)                      X S __MACRO_JOIN_53(S, __VA_ARGS__)
#define __MACRO_JOIN_55(S, X, ...)                      X S __MACRO_JOIN_54(S, __VA_ARGS__)
#define __MACRO_JOIN_56(S, X, ...)                      X S __MACRO_JOIN_55(S, __VA_ARGS__)
#define __MACRO_JOIN_57(S, X, ...)                      X S __MACRO_JOIN_56(S, __VA_ARGS__)
#define __MACRO_JOIN_58(S, X, ...)                      X S __MACRO_JOIN_57(S, __VA_ARGS__)
#define __MACRO_JOIN_59(S, X, ...)                      X S __MACRO_JOIN_58(S, __VA_ARGS__)
#define __MACRO_JOIN_60(S, X, ...)                      X S __MACRO_JOIN_59(S, __VA_ARGS__)
#define __MACRO_JOIN_61(S, X, ...)                      X S __MACRO_JOIN_60(S, __VA_ARGS__)
#define __MACRO_JOIN_62(S, X, ...)                      X S __MACRO_JOIN_61(S, __VA_ARGS__)
#define __MACRO_JOIN_63(S, X, ...)                      X S __MACRO_JOIN_62(S, __VA_ARGS__)
#define __MACRO_JOIN_64(S, X, ...)                      X S __MACRO_JOIN_63(S, __VA_ARGS__)
#define __MACRO_JOIN_65(S, X, ...)                      X S __MACRO_JOIN_64(S, __VA_ARGS__)
#define __MACRO_JOIN_66(S, X, ...)                      X S __MACRO_JOIN_65(S, __VA_ARGS__)
#define __MACRO_JOIN_67(S, X, ...)                      X S __MACRO_JOIN_66(S, __VA_ARGS__)
#define __MACRO_JOIN_68(S, X, ...)                      X S __MACRO_JOIN_67(S, __VA_ARGS__)
#define __MACRO_JOIN_69(S, X, ...)                      X S __MACRO_JOIN_68(S, __VA_ARGS__)
#define __MACRO_JOIN_70(S, X, ...)                      X S __MACRO_JOIN_69(S, __VA_ARGS__)
#define __MACRO_JOIN_71(S, X, ...)                      X S __MACRO_JOIN_70(S, __VA_ARGS__)
#define __MACRO_JOIN_72(S, X, ...)                      X S __MACRO_JOIN_71(S, __VA_ARGS__)
#define __MACRO_JOIN_73(S, X, ...)                      X S __MACRO_JOIN_72(S, __VA_ARGS__)
#define __MACRO_JOIN_74(S, X, ...)                      X S __MACRO_JOIN_73(S, __VA_ARGS__)
#define __MACRO_JOIN_75(S, X, ...)                      X S __MACRO_JOIN_74(S, __VA_ARGS__)
#define __MACRO_JOIN_76(S, X, ...)                      X S __MACRO_JOIN_75(S, __VA_ARGS__)
#define __MACRO_JOIN_77(S, X, ...)                      X S __MACRO_JOIN_76(S, __VA_ARGS__)
#define __MACRO_JOIN_78(S, X, ...)                      X S __MACRO_JOIN_77(S, __VA_ARGS__)
#define __MACRO_JOIN_79(S, X, ...)                      X S __MACRO_JOIN_78(S, __VA_ARGS__)
#define __MACRO_JOIN_80(S, X, ...)                      X S __MACRO_JOIN_79(S, __VA_ARGS__)
#define __MACRO_JOIN_81(S, X, ...)                      X S __MACRO_JOIN_80(S, __VA_ARGS__)
#define __MACRO_JOIN_82(S, X, ...)                      X S __MACRO_JOIN_81(S, __VA_ARGS__)
#define __MACRO_JOIN_83(S, X, ...)                      X S __MACRO_JOIN_82(S, __VA_ARGS__)
#define __MACRO_JOIN_84(S, X, ...)                      X S __MACRO_JOIN_83(S, __VA_ARGS__)
#define __MACRO_JOIN_85(S, X, ...)                      X S __MACRO_JOIN_84(S, __VA_ARGS__)
#define __MACRO_JOIN_86(S, X, ...)                      X S __MACRO_JOIN_85(S, __VA_ARGS__)
#define __MACRO_JOIN_87(S, X, ...)                      X S __MACRO_JOIN_86(S, __VA_ARGS__)
#define __MACRO_JOIN_88(S, X, ...)                      X S __MACRO_JOIN_87(S, __VA_ARGS__)
#define __MACRO_JOIN_89(S, X, ...)                      X S __MACRO_JOIN_88(S, __VA_ARGS__)
#define __MACRO_JOIN_90(S, X, ...)                      X S __MACRO_JOIN_89(S, __VA_ARGS__)
#define __MACRO_JOIN_91(S, X, ...)                      X S __MACRO_JOIN_90(S, __VA_ARGS__)
#define __MACRO_JOIN_92(S, X, ...)                      X S __MACRO_JOIN_91(S, __VA_ARGS__)
#define __MACRO_JOIN_93(S, X, ...)                      X S __MACRO_JOIN_92(S, __VA_ARGS__)
#define __MACRO_JOIN_94(S, X, ...)                      X S __MACRO_JOIN_93(S, __VA_ARGS__)
#define __MACRO_JOIN_95(S, X, ...)                      X S __MACRO_JOIN_94(S, __VA_ARGS__)
#define __MACRO_JOIN_96(S, X, ...)                      X S __MACRO_JOIN_95(S, __VA_ARGS__)
#define __MACRO_JOIN_97(S, X, ...)                      X S __MACRO_JOIN_96(S, __VA_ARGS__)
#define __MACRO_JOIN_98(S, X, ...)                      X S __MACRO_JOIN_97(S, __VA_ARGS__)
#define __MACRO_JOIN_99(S, X, ...)                      X S __MACRO_JOIN_98(S, __VA_ARGS__)

// ------------------------------------------------------------------------------------------------

#define __MACRO_JOIN_FN(SEP, FN, ...)                   __MACRO_JOIN_FN_ROOT(SEP, FN, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_JOIN_FN_ROOT(S, FN, N, ...)             __MACRO_JOIN_FN_ROOT_(S, FN, N, __VA_ARGS__)
#define __MACRO_JOIN_FN_ROOT_(S, FN, N, ...)            __MACRO_JOIN_FN_ ##N (S, FN, __VA_ARGS__)

#define __MACRO_JOIN_FN_0(S, FN, ...)                   __MACRO_FN(FN)
#define __MACRO_JOIN_FN_1(S, FN, X, ...)                __MACRO_FN(FN, X)
#define __MACRO_JOIN_FN_2(S, FN, X, ...)                __MACRO_FN(FN, X) S __MACRO_JOIN_FN_1(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_3(S, FN, X, ...)                __MACRO_FN(FN, X) S __MACRO_JOIN_FN_2(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_4(S, FN, X, ...)                __MACRO_FN(FN, X) S __MACRO_JOIN_FN_3(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_5(S, FN, X, ...)                __MACRO_FN(FN, X) S __MACRO_JOIN_FN_4(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_6(S, FN, X, ...)                __MACRO_FN(FN, X) S __MACRO_JOIN_FN_5(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_7(S, FN, X, ...)                __MACRO_FN(FN, X) S __MACRO_JOIN_FN_6(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_8(S, FN, X, ...)                __MACRO_FN(FN, X) S __MACRO_JOIN_FN_7(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_9(S, FN, X, ...)                __MACRO_FN(FN, X) S __MACRO_JOIN_FN_8(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_10(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_9(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_11(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_10(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_12(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_11(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_13(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_12(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_14(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_13(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_15(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_14(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_16(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_15(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_17(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_16(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_18(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_17(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_19(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_18(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_20(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_19(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_21(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_20(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_22(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_21(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_23(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_22(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_24(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_23(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_25(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_24(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_26(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_25(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_27(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_26(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_28(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_27(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_29(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_28(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_30(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_29(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_31(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_30(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_32(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_31(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_33(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_32(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_34(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_33(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_35(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_34(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_36(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_35(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_37(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_36(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_38(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_37(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_39(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_38(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_40(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_39(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_41(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_40(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_42(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_41(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_43(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_42(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_44(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_43(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_45(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_44(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_46(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_45(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_47(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_46(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_48(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_47(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_49(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_48(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_50(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_49(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_51(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_50(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_52(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_51(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_53(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_52(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_54(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_53(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_55(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_54(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_56(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_55(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_57(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_56(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_58(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_57(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_59(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_58(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_60(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_59(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_61(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_60(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_62(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_61(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_63(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_62(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_64(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_63(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_65(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_64(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_66(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_65(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_67(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_66(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_68(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_67(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_69(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_68(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_70(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_69(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_71(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_70(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_72(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_71(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_73(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_72(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_74(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_73(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_75(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_74(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_76(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_75(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_77(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_76(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_78(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_77(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_79(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_78(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_80(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_79(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_81(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_80(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_82(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_81(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_83(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_82(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_84(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_83(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_85(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_84(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_86(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_85(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_87(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_86(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_88(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_87(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_89(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_88(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_90(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_89(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_91(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_90(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_92(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_91(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_93(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_92(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_94(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_93(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_95(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_94(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_96(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_95(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_97(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_96(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_98(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_97(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_99(S, FN, X, ...)               __MACRO_FN(FN, X) S __MACRO_JOIN_FN_98(S, FN, __VA_ARGS__)

// ------------------------------------------------------------------------------------------------

#define __MACRO_JOIN_FN_ARG(SEP, FN, ARG, ...)          __MACRO_JOIN_FN_ARG_ROOT(SEP, FN, ARG, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_JOIN_FN_ARG_ROOT(S, FN, ARG, N, ...)    __MACRO_JOIN_FN_ARG_ROOT_(S, FN, ARG, N, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_ROOT_(S, FN, ARG, N, ...)   __MACRO_JOIN_FN_ARG_ ##N (S, FN, ARG, __VA_ARGS__)

#define __MACRO_JOIN_FN_ARG_0(S, FN, ARG, ...)          __MACRO_FN(FN, ARG)
#define __MACRO_JOIN_FN_ARG_1(S, FN, ARG, X, ...)       __MACRO_FN(FN, ARG, X)
#define __MACRO_JOIN_FN_ARG_2(S, FN, ARG, X, ...)       __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_1(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_3(S, FN, ARG, X, ...)       __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_2(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_4(S, FN, ARG, X, ...)       __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_3(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_5(S, FN, ARG, X, ...)       __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_4(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_6(S, FN, ARG, X, ...)       __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_5(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_7(S, FN, ARG, X, ...)       __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_6(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_8(S, FN, ARG, X, ...)       __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_7(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_9(S, FN, ARG, X, ...)       __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_8(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_10(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_9(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_11(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_10(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_12(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_11(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_13(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_12(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_14(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_13(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_15(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_14(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_16(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_15(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_17(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_16(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_18(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_17(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_19(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_18(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_20(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_19(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_21(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_20(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_22(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_21(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_23(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_22(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_24(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_23(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_25(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_24(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_26(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_25(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_27(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_26(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_28(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_27(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_29(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_28(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_30(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_29(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_31(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_30(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_32(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_31(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_33(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_32(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_34(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_33(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_35(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_34(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_36(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_35(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_37(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_36(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_38(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_37(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_39(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_38(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_40(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_39(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_41(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_40(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_42(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_41(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_43(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_42(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_44(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_43(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_45(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_44(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_46(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_45(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_47(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_46(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_48(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_47(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_49(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_48(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_50(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_49(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_51(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_50(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_52(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_51(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_53(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_52(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_54(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_53(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_55(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_54(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_56(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_55(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_57(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_56(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_58(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_57(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_59(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_58(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_60(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_59(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_61(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_60(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_62(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_61(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_63(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_62(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_64(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_63(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_65(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_64(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_66(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_65(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_67(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_66(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_68(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_67(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_69(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_68(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_70(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_69(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_71(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_70(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_72(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_71(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_73(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_72(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_74(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_73(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_75(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_74(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_76(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_75(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_77(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_76(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_78(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_77(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_79(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_78(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_80(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_79(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_81(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_80(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_82(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_81(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_83(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_82(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_84(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_83(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_85(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_84(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_86(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_85(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_87(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_86(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_88(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_87(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_89(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_88(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_90(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_89(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_91(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_90(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_92(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_91(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_93(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_92(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_94(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_93(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_95(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_94(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_96(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_95(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_97(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_96(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_98(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_97(S, FN, ARG, __VA_ARGS__)
#define __MACRO_JOIN_FN_ARG_99(S, FN, ARG, X, ...)      __MACRO_FN(FN, ARG, X) S __MACRO_JOIN_FN_ARG_98(S, FN, ARG, __VA_ARGS__)

// ------------------------------------------------------------------------------------------------

#define __MACRO_JOIN_FN_TUPLE(SEP, FN, ...)             __MACRO_JOIN_FN_TUPLE_ROOT(SEP, FN, __MACRO_VA_ARGS_LEN(__VA_ARGS__), __VA_ARGS__)

#define __MACRO_JOIN_FN_TUPLE_ROOT(S, FN, N, ...)       __MACRO_JOIN_FN_TUPLE_ROOT_(S, FN, N, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_ROOT_(S, FN, N, ...)      __MACRO_JOIN_FN_TUPLE_ ##N (S, FN, __VA_ARGS__)

#define __MACRO_JOIN_FN_TUPLE_0(S, FN, ...)             __MACRO_FN(FN)
#define __MACRO_JOIN_FN_TUPLE_1(S, FN, X, ...)          __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X))
#define __MACRO_JOIN_FN_TUPLE_2(S, FN, X, ...)          __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_1(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_3(S, FN, X, ...)          __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_2(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_4(S, FN, X, ...)          __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_3(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_5(S, FN, X, ...)          __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_4(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_6(S, FN, X, ...)          __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_5(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_7(S, FN, X, ...)          __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_6(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_8(S, FN, X, ...)          __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_7(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_9(S, FN, X, ...)          __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_8(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_10(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_9(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_11(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_10(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_12(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_11(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_13(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_12(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_14(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_13(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_15(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_14(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_16(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_15(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_17(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_16(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_18(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_17(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_19(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_18(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_20(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_19(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_21(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_20(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_22(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_21(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_23(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_22(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_24(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_23(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_25(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_24(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_26(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_25(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_27(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_26(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_28(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_27(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_29(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_28(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_30(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_29(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_31(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_30(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_32(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_31(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_33(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_32(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_34(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_33(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_35(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_34(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_36(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_35(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_37(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_36(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_38(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_37(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_39(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_38(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_40(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_39(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_41(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_40(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_42(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_41(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_43(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_42(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_44(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_43(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_45(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_44(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_46(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_45(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_47(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_46(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_48(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_47(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_49(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_48(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_50(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_49(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_51(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_50(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_52(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_51(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_53(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_52(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_54(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_53(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_55(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_54(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_56(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_55(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_57(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_56(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_58(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_57(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_59(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_58(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_60(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_59(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_61(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_60(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_62(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_61(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_63(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_62(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_64(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_63(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_65(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_64(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_66(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_65(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_67(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_66(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_68(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_67(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_69(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_68(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_70(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_69(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_71(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_70(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_72(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_71(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_73(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_72(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_74(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_73(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_75(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_74(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_76(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_75(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_77(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_76(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_78(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_77(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_79(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_78(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_80(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_79(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_81(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_80(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_82(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_81(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_83(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_82(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_84(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_83(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_85(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_84(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_86(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_85(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_87(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_86(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_88(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_87(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_89(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_88(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_90(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_89(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_91(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_90(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_92(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_91(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_93(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_92(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_94(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_93(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_95(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_94(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_96(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_95(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_97(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_96(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_98(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_97(S, FN, __VA_ARGS__)
#define __MACRO_JOIN_FN_TUPLE_99(S, FN, X, ...)         __MACRO_FN(FN, __MACRO_TUPLE_EXPAND(X)) S __MACRO_JOIN_FN_TUPLE_98(S, FN, __VA_ARGS__)

#endif // _MACRO_JOIN_H_
